### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by newman1234** [fbrundu/pymrmr#119]
* PymRMR version: 0.1.8
* Python version: Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
* Operating System: Windows 10

### Description

I try to install pymrmr but failed

### What I Did

I try $pip install pymrmr
but it gives me
![image](https://user-images.githubusercontent.com/17400517/40640430-9518f7d8-6348-11e8-9a8f-7773fa521391.png)

Any ideas?  thanks.

**Comment by fbrundu** [comment]
Dear @newman1234,
It seems you do not have Microsoft Visual Studio C++ installed. Try to follow the link in your error output and you should be able to install pymrmr.
If not, feel free to reopen this issue.

Francesco
