### ISSUE TITLE
pymrmr.mRMR give error AttributeError: 'numpy.int64' object has no attribute 'encode'

### ISSUE THREAD

**Issue by minmingzhao** [fbrundu/pymrmr#63]
* PymRMR version: pymrmr 0.1.8
* Python version: 3.6
* Operating System: Windows 7

### Description
When I run `ret = pymrmr.mRMR(df,'MIQ',36)`, which df = [y, X] with 7million row and 84 column. I have error of `Traceback (most recent call last):

  File "<ipython-input-117-6a76f7a34f69>", line 1, in <module>
    ret = pymrmr.mRMR(df,'MIQ',36)

  File "pymrmr/pymrmr.pyx", line 20, in pymrmr.mRMR (pymrmr\pymrmr.cpp:1723)

AttributeError: 'numpy.int64' object has no attribute 'encode' `

Could you please help? Thanks!

**Comment by minmingzhao** [comment]
Ok. I think I realized why. The columns of dataframe for pymrmr.mRMR() has to be string.

**Comment by fbrundu** [comment]
Dear @minmingzhao, yes the column names of the dataframe should be strings. Thanks for highlighting this and sorry for the delay.
