### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Gautamshahi** [fbrundu/pymrmr#89]
I am getting an installation error, kindly help me to resolve it

![image](https://user-images.githubusercontent.com/3966230/36071993-e0bd9d56-0f3d-11e8-95f0-2c60518e8a94.png)

**Comment by fbrundu** [comment]
Hey @Gautamshahi,
It seems that you may be missing cl.exe from Visual Studio, needed to build the library. Try this solution:

https://stackoverflow.com/questions/31953769/visual-studio-doesnt-have-cl-exe

Francesco

**Comment by Gautamshahi** [comment]
Hi,

Thnak you.

Now I am getting the below error, I tried to install mRMR also but unable to do it, could you please help in it?

![image](https://user-images.githubusercontent.com/3966230/36080281-c893827e-0fb3-11e8-9354-046354983bed.png)

**Comment by fbrundu** [comment]
I think you are trying to execute directly the module (which cannot be executed from the command line).

You should import the module from another python script, or through ipython. For instance, you can follow the example on the README. You should then pass a pandas DataFrame to the module method. This is an example of execution on ipython:

```
In [1]: import pandas as pd

In [2]: import pymrmr

In [3]: df = pd.read_csv('test_colon_s3.csv')

In [4]: pymrmr.mRMR(df, 'MIQ', 10)


 *** This program and the respective minimum Redundancy Maximum Relevance (mRMR)
     algorithm were developed by Hanchuan Peng <hanchuan.peng@gmail.com>for
     the paper
     "Feature selection based on mutual information: criteria of
      max-dependency, max-relevance, and min-redundancy,"
      Hanchuan Peng, Fuhui Long, and Chris Ding,
      IEEE Transactions on Pattern Analysis and Machine Intelligence,
      Vol. 27, No. 8, pp.1226-1238, 2005.


 *** MaxRel features ***
 Order    Fea     Name    Score
 1        765     v765    0.375
 2        1423    v1423   0.337
 3        513     v513    0.321
 4        249     v249    0.309
 5        267     v267    0.304
 6        245     v245    0.304
 7        1582    v1582   0.280
 8        897     v897    0.269
 9        1771    v1771   0.269
 10       1772    v1772   0.269

 *** mRMR features ***
 Order    Fea     Name    Score
 1        765     v765    0.375
 2        1123    v1123   24.913
 3        1772    v1772   3.984
 4        286     v286    2.280
 5        467     v467    1.979
 6        377     v377    1.768
 7        513     v513    1.803
 8        1325    v1325   1.634
 9        1972    v1972   1.741
 10       1412    v1412   1.689
 Out[4]:
 ['v765',
  'v1123',
  'v1772',
  'v286',
  'v467',
  'v377',
  'v513',
  'v1325',
  'v1972',
  'v1412']
```

Closing because your problem seems solved. Reopen or create a new issue if you get a different problem.

Francesco
