### ISSUE TITLE
Library not loaded: /usr/local/opt/libiomp/lib/libiomp5.dylib

### ISSUE THREAD

**Issue by joelrorseth** [fbrundu/pymrmr#98]
* PymRMR version: 0.1.8
* Python version: 3.6.4
* Operating System: macOS 10.12.6

### Description

I've been trying to run a quick Python program, but it seems that the pymrmr code cannot find libiomp5. I'm not sure what that is, I didn't see it listed in the dependencies here.

### What I Did

```
> python3 gene_selection.py
Traceback (most recent call last):
  File "gene_selection.py", line 8, in <module>
    import pymrmr
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/pymrmr.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/libiomp/lib/libiomp5.dylib
  Referenced from: /usr/local/lib/python3.6/site-packages/pymrmr.cpython-36m-darwin.so
  Reason: image not found
```

**Comment by fbrundu** [comment]
Hi Joel,
It seems that OpenMP is not available on your machine. If you have Homebrew, could you please see if install `llvm` solves this problem?

    brew install llvm

As per https://stackoverflow.com/a/39843038/41977

Francesco

**Comment by runarbu** [comment]
Thank you fbrundu 

I had almost the same error: 
```
OSError: dlopen(/Users/username/path/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/username/.local/share/virtualenvs/repo/lib/python3.6/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found
```


Installing llvm fixed it for me.

**Comment by Iven-Wang** [comment]
> I had same error
> 
> I installed libomp then, it works.
> 
> ```
> brew install libomp
> ```

Solved!!!!! Thanks!!!!!!!

**Comment by Reshma2k** [comment]
I got an error while installing libomp  as follows:
-bash: brew: command not found

I tried installing it in terminal on Mac OS X

**Comment by fbrundu** [comment]
Hi @Reshma2k . You should install homebrew first: https://brew.sh

**Comment by Reshma2k** [comment]
It helps. Thanks!

**Comment by hainow** [comment]
> > I had same error
> > I installed libomp then, it works.
> > ```
> > brew install libomp
> > ```
> 
> Solved!!!!! Thanks!!!!!!!

Solved for me too. Thanks a lot!

**Comment by gurpreetsingh2410** [comment]
> > ```
> > brew install libomp
> > ```

Solved it for me too. Thanks.

**Comment by lisherlock** [comment]
It works, thanks very much!

**Comment by songxiang666** [comment]
I have installed libomp and llvm, but it does not work for me.
- pymrmr version (0.1.8)
- python version (3.6.7)
- OS (Mac OS 10.14.5)
